package com.atlas.intake;

public enum InterviewStage {
    // Required services-row fields
    AWAITING_NAME,
    AWAITING_DESCRIPTION,
    AWAITING_DESCRIPTION_CLARIFICATION,
    AWAITING_OWNER_TEAM,
    AWAITING_STATUS,

    // Optional services-row fields (M1)
    AWAITING_LANGUAGE,
    AWAITING_FRAMEWORK,
    AWAITING_REPO_URL,
    AWAITING_DEPLOYMENT,
    AWAITING_SUPPORT_CONTACT,
    AWAITING_SLA,
    AWAITING_NOTES,

    // APIs section (M2)
    AWAITING_HAS_APIS,
    AWAITING_API_PATH,
    AWAITING_API_METHOD,
    AWAITING_API_AUTH,
    AWAITING_API_DESCRIPTION,
    AWAITING_ANOTHER_API,

    // Upstream service-to-service dependencies (M2)
    AWAITING_HAS_UPSTREAM_DEPS,
    AWAITING_UPSTREAM_NAME,
    AWAITING_UPSTREAM_DESCRIPTION,
    AWAITING_ANOTHER_UPSTREAM,

    // Downstream service-to-service dependencies (M2)
    AWAITING_HAS_DOWNSTREAM_DEPS,
    AWAITING_DOWNSTREAM_NAME,
    AWAITING_DOWNSTREAM_DESCRIPTION,
    AWAITING_ANOTHER_DOWNSTREAM
}
