package com.atlas.intake;

public enum InterviewStage {
    AWAITING_NAME,
    AWAITING_DESCRIPTION,
    AWAITING_DESCRIPTION_CLARIFICATION,
    AWAITING_OWNER_TEAM,
    AWAITING_STATUS,
    AWAITING_LANGUAGE,
    AWAITING_FRAMEWORK,
    AWAITING_REPO_URL,
    AWAITING_DEPLOYMENT,
    AWAITING_SUPPORT_CONTACT,
    AWAITING_SLA,
    AWAITING_NOTES
}
