package com.atlas.intake;

public enum InterviewStage {
    // Required services-row fields
    AWAITING_NAME,
    AWAITING_DESCRIPTION,
    AWAITING_DESCRIPTION_CLARIFICATION,
    AWAITING_OWNER_TEAM,
    AWAITING_STATUS,

    // Optional services-row fields (M1)
    AWAITING_LANGUAGE,
    AWAITING_FRAMEWORK,
    AWAITING_REPO_URL,
    AWAITING_DEPLOYMENT,
    AWAITING_SUPPORT_CONTACT,
    AWAITING_SLA,
    AWAITING_NOTES,

    // APIs section (M2 / Phase 3.6)
    AWAITING_HAS_APIS,
    AWAITING_API_PATH,
    AWAITING_API_METHOD,
    AWAITING_API_AUTH,
    AWAITING_API_DESCRIPTION,
    // Consumers sub-loop within each API (Phase 3.6)
    AWAITING_HAS_API_CONSUMERS,
    AWAITING_API_CONSUMER_NAME,
    AWAITING_API_CONSUMER_DESCRIPTION,
    AWAITING_ANOTHER_API_CONSUMER,
    AWAITING_ANOTHER_API,

    // Upstream service-to-service dependencies (M2)
    AWAITING_HAS_UPSTREAM_DEPS,
    AWAITING_UPSTREAM_NAME,
    AWAITING_UPSTREAM_DESCRIPTION,
    AWAITING_ANOTHER_UPSTREAM,

    // Downstream service-to-service dependencies (M2)
    AWAITING_HAS_DOWNSTREAM_DEPS,
    AWAITING_DOWNSTREAM_NAME,
    AWAITING_DOWNSTREAM_DESCRIPTION,
    AWAITING_ANOTHER_DOWNSTREAM,

    // Databases section (M3) — lookup-or-create
    AWAITING_HAS_DATABASES,
    AWAITING_DATABASE_NAME,
    AWAITING_DATABASE_ENGINE,           // only asked when creating new
    AWAITING_DATABASE_IS_OWNER,
    AWAITING_DATABASE_LINK_DESCRIPTION,
    AWAITING_ANOTHER_DATABASE,

    // External dependencies section (M3) — lookup-or-create
    AWAITING_HAS_EXTERNAL_DEPS,
    AWAITING_EXTERNAL_DEP_NAME,
    AWAITING_EXTERNAL_DEP_URL,          // only asked when creating new
    AWAITING_EXTERNAL_DEP_LINK_DESCRIPTION,
    AWAITING_ANOTHER_EXTERNAL_DEP
}
